// New clients use a 128-bit nonce. Accept the 256-bit value generated by the
// first Electron 3.0 build as well so connection links already open in a
// browser continue to work during the upgrade.
const CONNECT_STATE = /^(?:[a-f0-9]{32}|[a-f0-9]{64})$/i;

/** State is a hexadecimal nonce generated by the desktop app before opening the browser. */
export function isValidConnectState(value: unknown): value is string {
  return typeof value === "string" && CONNECT_STATE.test(value);
}

export function normalizeDeviceName(value: unknown): string {
  if (typeof value !== "string") return "Desktop";
  const clean = value.replace(/[\u0000-\u001F\u007F]/g, " ").replace(/\s+/g, " ").trim().slice(0, 80);
  return clean || "Desktop";
}
