const CONNECT_STATE = /^[a-f0-9]{32}$/i;

/** State is a 128-bit nonce generated by the desktop app before opening the browser. */
export function isValidConnectState(value: unknown): value is string {
  return typeof value === "string" && CONNECT_STATE.test(value);
}

export function normalizeDeviceName(value: unknown): string {
  if (typeof value !== "string") return "Desktop";
  const clean = value.replace(/[\u0000-\u001F\u007F]/g, " ").replace(/\s+/g, " ").trim().slice(0, 80);
  return clean || "Desktop";
}
