import type {
  AuditTemplate,
  AuditTestRun,
  AuditTestStepResult,
} from "../shared/desktop";

export interface AuditTestScript {
  id: string;
  title: string;
  category: AuditTestRun["category"];
  description: string;
  steps: string[];
}

export const AUDIT_TEST_SCRIPTS: AuditTestScript[] = [
  {
    id: "authentication",
    title: "Authentication and account recovery",
    category: "authentication",
    description: "Verify sign in, validation, recovery, timeout, and authenticated state changes.",
    steps: [
      "Complete sign in using only the keyboard and verify a visible focus indicator.",
      "Trigger every validation error and confirm it is announced, associated, and understandable.",
      "Complete password or account recovery without relying on memory, color, or a pointer.",
      "Verify timeout warnings can be extended and restored without losing entered information.",
      "Confirm status changes and authentication errors are exposed to assistive technology.",
    ],
  },
  {
    id: "checkout",
    title: "Cart and checkout journey",
    category: "checkout",
    description: "Evaluate discovery, cart updates, payment, errors, and order confirmation as one task.",
    steps: [
      "Find a product and add it to the cart at 200% zoom and with keyboard-only input.",
      "Change quantity, remove an item, and confirm updated totals are announced.",
      "Complete address and payment fields with a screen reader and autocomplete enabled.",
      "Trigger payment and address errors, then recover without losing valid information.",
      "Confirm the order review and success states expose names, totals, and status changes.",
    ],
  },
  {
    id: "forms",
    title: "Forms and validation",
    category: "forms",
    description: "Check labels, instructions, input purpose, errors, review, and submission feedback.",
    steps: [
      "Navigate every field in a logical order using the keyboard and a screen reader.",
      "Confirm visible labels and programmatic names remain present after values are entered.",
      "Verify required format, autocomplete, and input-purpose information is exposed.",
      "Submit invalid data and confirm errors identify the field and explain recovery.",
      "Submit valid data and confirm success or processing status is announced.",
    ],
  },
  {
    id: "media",
    title: "Audio, video, and animation",
    category: "media",
    description: "Review alternatives, captions, descriptions, controls, autoplay, and flashing content.",
    steps: [
      "Verify prerecorded video has synchronized captions and an equivalent audio description or alternative.",
      "Verify live media provides captions when required by the evaluation target.",
      "Operate play, pause, volume, seek, captions, and full-screen controls with keyboard and screen reader.",
      "Confirm automatically playing audio can be paused or stopped independently.",
      "Check animation, flashing, and motion-triggered interactions for pause and reduced-motion behavior.",
    ],
  },
  {
    id: "documents",
    title: "Documents and downloadable content",
    category: "documents",
    description: "Review document structure, reading order, alternatives, tables, forms, and metadata.",
    steps: [
      "Open each document from its published link and record the format and reader used.",
      "Verify title, language, headings, lists, landmarks, and reading order are meaningful.",
      "Check images, charts, links, tables, and form controls for appropriate alternatives and structure.",
      "Navigate the document using keyboard and assistive-technology shortcuts.",
      "Confirm visible content and annotations are not omitted from the accessibility tree.",
    ],
  },
  {
    id: "components",
    title: "Design-system component coverage",
    category: "components",
    description: "Test reusable controls in default, interactive, validation, disabled, and responsive states.",
    steps: [
      "Inventory the component variants and states used by the representative sample.",
      "Verify name, role, value, instructions, and state changes for each interactive variant.",
      "Check keyboard order, activation, dismissal, and focus restoration.",
      "Evaluate default, hover, focus, selected, disabled, loading, error, and success states.",
      "Repeat at 320 CSS pixels, 200% zoom, forced colors, and reduced motion where applicable.",
    ],
  },
];

export const BUILT_IN_AUDIT_TEMPLATES: AuditTemplate[] = [
  {
    id: "content-site-aa",
    name: "Content website, WCAG 2.2 AA",
    description: "A representative evaluation of public pages, navigation, content patterns, forms, media, and downloads.",
    source: "built-in",
    targetType: "content-site",
    featureIds: ["forms", "media", "documents", "components"],
    goal: "Evaluate representative public content and essential interactions against WCAG 2.2 Level A and AA.",
    scope: "Global navigation, shared page templates, content structure, search, contact or subscription forms, media, downloads, responsive layouts, and error states.",
    sample: "Include each shared page template, the highest-traffic and highest-risk content types, one long-form page, one form, one media example, and each materially different navigation pattern.",
    excludedScope: "Record archived content, third-party embeds, authenticated areas, and unavailable source documents before testing begins.",
    environment: "Chrome and Edge on Windows 11; Safari on current macOS and iOS; 320 CSS pixels; 200% and 400% zoom; text-spacing overrides; forced colors; reduced motion.",
    assistiveTechnology: "Keyboard-only; NVDA with Chrome; VoiceOver with Safari on macOS and iOS; Windows High Contrast; browser text-spacing overrides.",
    methodology: "Manual WCAG review of the documented representative sample, supported by deterministic tools, keyboard testing, screen-reader verification, responsive reflow checks, and evidence capture. Automated results remain unconfirmed until reviewed by an auditor.",
    standard: "WCAG 2.2 AA",
    sampleItems: [
      { kind: "page", label: "Home and primary navigation", location: "", notes: "Include header, footer, menus, search, and responsive navigation." },
      { kind: "page", label: "Representative content template", location: "", notes: "Include headings, links, images, lists, tables, and long-form content." },
      { kind: "flow", label: "Primary public interaction", location: "", notes: "Include validation, confirmation, and recovery states." },
    ],
    testScriptIds: ["forms", "media", "documents", "components"],
  },
  {
    id: "web-product-aa",
    name: "Web product, WCAG 2.2 AA",
    description: "A cross-browser, keyboard, screen-reader, zoom, and responsive product evaluation.",
    source: "built-in",
    targetType: "web-product",
    featureIds: ["authentication", "forms", "components"],
    goal: "Evaluate critical user journeys and reusable components against WCAG 2.2 Level A and AA.",
    scope: "Critical user journeys, shared templates, navigation, forms, errors, authenticated states, and downloadable content.",
    sample: "Include every shared template, critical task, repeated component, error state, and materially different responsive layout.",
    excludedScope: "Record third-party and unavailable states before testing begins.",
    environment: "Chrome and Edge on Windows 11; Safari on current macOS; Safari on iOS; 320 CSS pixels; 200% and 400% zoom; forced colors; reduced motion.",
    assistiveTechnology: "Keyboard-only; NVDA with Chrome; VoiceOver with Safari on macOS and iOS; browser text-spacing overrides; Windows High Contrast.",
    methodology: "Manual WCAG review following the documented representative sample, supported by deterministic tools, keyboard testing, screen-reader verification, responsive reflow checks, and evidence capture. Automated results remain unconfirmed until reviewed by an auditor.",
    standard: "WCAG 2.2 AA",
    sampleItems: [
      { kind: "flow", label: "Primary critical journey", location: "", notes: "Include success, error, and recovery states." },
      { kind: "component", label: "Global navigation and shared controls", location: "", notes: "Test every repeated state and breakpoint." },
      { kind: "page", label: "Content-heavy representative page", location: "", notes: "Include headings, links, images, and tables where present." },
    ],
    testScriptIds: ["authentication", "forms", "components"],
  },
  {
    id: "commerce-service",
    name: "Commerce or transactional service",
    description: "An end-to-end evaluation of discovery, account, transaction, validation, payment, and confirmation journeys.",
    source: "built-in",
    targetType: "commerce-service",
    featureIds: ["authentication", "checkout", "forms", "components"],
    goal: "Evaluate whether customers can discover, select, purchase, book, apply, or complete another critical transaction against WCAG 2.2 Level A and AA.",
    scope: "Discovery and search, item or service details, account access, selection or cart changes, checkout or application steps, validation, payment, confirmation, cancellation, and reusable transactional components.",
    sample: "Include the primary successful transaction, validation and payment failures, recovery and cancellation, an account or guest path, representative product or service content, and every shared transactional component.",
    excludedScope: "Record third-party payment, identity, fraud, or fulfillment surfaces that cannot be directly evaluated, including the boundary and alternative path.",
    environment: "Chrome and Edge on Windows 11; Safari on current macOS and iOS; 320 CSS pixels; 200% and 400% zoom; forced colors; reduced motion; representative touch input.",
    assistiveTechnology: "Keyboard-only; NVDA with Chrome; VoiceOver with Safari on macOS and iOS; Windows High Contrast; browser text-spacing overrides; voice input for critical forms.",
    methodology: "Task-based manual WCAG review of complete successful and failed transactions, supported by keyboard, screen-reader, zoom, reflow, error-recovery, status-message, and evidence testing. Automated results remain signals until confirmed by an auditor.",
    standard: "WCAG 2.2 AA",
    sampleItems: [
      { kind: "flow", label: "Primary successful transaction", location: "", notes: "Cover discovery through confirmation without a pointer." },
      { kind: "state", label: "Validation, payment, and recovery states", location: "", notes: "Trigger and recover from each material failure." },
      { kind: "component", label: "Shared transactional controls", location: "", notes: "Cover search, selection, totals, progress, and confirmation patterns." },
    ],
    testScriptIds: ["authentication", "checkout", "forms", "components"],
  },
  {
    id: "release-regression",
    name: "Release regression",
    description: "A focused reassessment of critical flows, fixed findings, and shared components before release.",
    source: "built-in",
    targetType: "release-regression",
    featureIds: ["components"],
    goal: "Confirm previously fixed barriers remain resolved and the release introduces no regression in critical tasks.",
    scope: "Previously failed criteria, remediated components, affected user journeys, and release-specific interface changes.",
    sample: "Prioritize every remediated component and each critical journey that uses it, plus one unaffected baseline flow.",
    excludedScope: "Unchanged areas not connected to remediated or release-specific components.",
    environment: "The same browser, operating-system, viewport, zoom, and build combinations used for the original finding, plus the primary supported production browser.",
    assistiveTechnology: "The same assistive technology used for the original finding, plus keyboard-only verification.",
    methodology: "Reproduce the original failure, capture before and after evidence, repeat the original test in the release candidate, and verify adjacent component states for regression.",
    standard: "WCAG 2.2 AA",
    sampleItems: [
      { kind: "flow", label: "Critical release journey", location: "", notes: "Retest fixed findings in context." },
      { kind: "component", label: "Remediated shared component", location: "", notes: "Cover every affected variant and state." },
    ],
    testScriptIds: ["components"],
  },
  {
    id: "desktop-product",
    name: "Desktop application",
    description: "A native desktop evaluation across keyboard, accessibility APIs, scaling, and system preferences.",
    source: "built-in",
    targetType: "desktop-product",
    featureIds: ["forms", "components"],
    goal: "Evaluate critical desktop workflows, native semantics, keyboard access, focus behavior, and system preference support.",
    scope: "Application shell, menus, dialogs, critical workflows, editable content, notifications, updates, and system integrations.",
    sample: "Include each primary window type, modal and non-modal flow, reusable control family, empty state, error state, and permission state.",
    excludedScope: "Document operating-system dialogs or embedded third-party surfaces evaluated separately.",
    environment: "Current and previous supported macOS releases on Apple silicon; Windows 11 at 100%, 200%, and high-contrast settings; high-DPI and multi-monitor configurations.",
    assistiveTechnology: "Keyboard-only; VoiceOver on macOS; NVDA on Windows; Voice Control or Windows Voice Access; increased contrast; reduced motion.",
    methodology: "Manual application testing using native accessibility APIs, keyboard operation, assistive technology, display scaling, system appearance preferences, and annotated evidence capture.",
    standard: "WCAG 2.2 AA",
    sampleItems: [
      { kind: "flow", label: "Primary desktop workflow", location: "", notes: "Include menus, dialogs, and completion feedback." },
      { kind: "state", label: "Permission, empty, loading, and error states", location: "", notes: "Verify recovery and announcements." },
      { kind: "component", label: "Reusable desktop controls", location: "", notes: "Include focus, disabled, and selected states." },
    ],
    testScriptIds: ["forms", "components"],
  },
  {
    id: "mobile-product",
    name: "Mobile application",
    description: "A native mobile evaluation across touch, external keyboard, platform semantics, orientation, scaling, and assistive technology.",
    source: "built-in",
    targetType: "mobile-product",
    featureIds: ["authentication", "forms", "media", "components"],
    goal: "Evaluate critical mobile workflows, native semantics, touch operation, focus, scaling, orientation, and platform accessibility support.",
    scope: "Application shell, onboarding, account access, primary tasks, navigation, forms, dialogs, notifications, media, permissions, deep links, and reusable mobile controls.",
    sample: "Include each primary screen family, critical gesture and keyboard path, modal and non-modal flow, empty and error state, permission state, orientation, and dynamic text size.",
    excludedScope: "Record operating-system dialogs, embedded web views, third-party SDK surfaces, and device-specific features evaluated separately.",
    environment: "Current supported iOS and Android releases; representative phone and tablet sizes; portrait and landscape; largest supported text; increased contrast; reduced motion; external keyboard.",
    assistiveTechnology: "VoiceOver on iOS; TalkBack on Android; external keyboard; Voice Control or Voice Access; Switch Control or Switch Access where applicable; platform display and motion preferences.",
    methodology: "Task-based manual application testing using native accessibility APIs, touch exploration, gestures, external keyboard, assistive technology, orientation, dynamic text, system preferences, and evidence capture.",
    standard: "WCAG 2.2 AA",
    sampleItems: [
      { kind: "flow", label: "Primary mobile workflow", location: "", notes: "Include touch, screen-reader, and external-keyboard paths." },
      { kind: "state", label: "Permission, empty, loading, and error states", location: "", notes: "Verify announcements, focus, and recovery." },
      { kind: "component", label: "Reusable mobile controls", location: "", notes: "Include gesture alternatives, target size, state, and large text." },
    ],
    testScriptIds: ["authentication", "forms", "media", "components"],
  },
  {
    id: "document-set",
    name: "Document collection",
    description: "A structured sample for PDFs, office documents, and downloadable forms.",
    source: "built-in",
    targetType: "document-set",
    featureIds: ["documents"],
    goal: "Evaluate representative downloadable documents for structure, reading order, alternatives, navigation, and forms.",
    scope: "Published PDFs, office documents, forms, policy files, reports, and linked alternatives included in the representative sample.",
    sample: "Include every document template, authoring source, document type, complex table pattern, form pattern, and high-priority public document.",
    excludedScope: "Record archived, superseded, or inaccessible source documents separately.",
    environment: "Adobe Acrobat Reader and browser PDF viewers on Windows and macOS; source application where remediation is expected.",
    assistiveTechnology: "NVDA with Acrobat Reader; VoiceOver with Preview or Safari; keyboard-only navigation; high zoom and reflow where supported.",
    methodology: "Manual document structure and reading-order review supported by accessibility checkers. Tool results remain signals until verified against rendered and assistive-technology behavior.",
    standard: "WCAG 2.2 AA",
    sampleItems: [
      { kind: "document", label: "Representative simple document", location: "", notes: "Check title, language, headings, links, and reading order." },
      { kind: "document", label: "Complex table or visual report", location: "", notes: "Check table structure and equivalent descriptions." },
      { kind: "document", label: "Interactive form document", location: "", notes: "Check labels, order, validation, and submission." },
    ],
    testScriptIds: ["documents"],
  },
  {
    id: "component-library",
    name: "Design system or component library",
    description: "A state-complete evaluation of reusable components, documented patterns, tokens, and implementation guidance.",
    source: "built-in",
    targetType: "component-library",
    featureIds: ["forms", "media", "components"],
    goal: "Evaluate reusable interface components and documented patterns so accessibility defects are addressed at their shared source.",
    scope: "Foundations and tokens, component variants, interactive states, composite patterns, form controls, overlays, navigation, media controls, responsive behavior, and implementation guidance.",
    sample: "Include every component family and materially different variant across default, hover, focus, active, selected, disabled, loading, empty, validation, error, success, and responsive states.",
    excludedScope: "Record product-specific compositions, downstream overrides, deprecated components, and third-party primitives separately.",
    environment: "Chrome and Edge on Windows 11; Safari on current macOS; 320 CSS pixels; 200% and 400% zoom; forced colors; reduced motion; text-spacing overrides.",
    assistiveTechnology: "Keyboard-only; NVDA with Chrome; VoiceOver with Safari; Windows High Contrast; browser text-spacing overrides; voice input for labeled controls.",
    methodology: "State-by-state manual evaluation of isolated components and representative compositions, supported by accessibility-tree inspection, keyboard and screen-reader testing, responsive checks, and documented consumer guidance.",
    standard: "WCAG 2.2 AA",
    sampleItems: [
      { kind: "component", label: "Foundations and simple controls", location: "", notes: "Cover tokens, text, links, buttons, icons, and inputs." },
      { kind: "component", label: "Composite and overlay patterns", location: "", notes: "Cover menus, dialogs, tabs, disclosures, grids, and focus restoration." },
      { kind: "state", label: "Validation and asynchronous states", location: "", notes: "Cover loading, empty, error, success, and live updates." },
    ],
    testScriptIds: ["forms", "media", "components"],
  },
];

export function createTestRun(script: AuditTestScript): AuditTestRun {
  const now = Date.now();
  const steps: AuditTestStepResult[] = script.steps.map((label, index) => ({
    id: `${script.id}-${index + 1}`,
    label,
    complete: false,
    observation: "",
  }));
  return {
    id: crypto.randomUUID(),
    scriptId: script.id,
    title: script.title,
    category: script.category,
    status: "planned",
    steps,
    notes: "",
    createdAt: now,
    modifiedAt: now,
  };
}
